logging:
  level:
    org:
      fool:
        redis: debug
server:
  port: 8888
spring:
  application:
    name: redis-lock-setnx
  redis:
    database: 0
    host: 172.25.17.131
    password: 123456
    pool:
      block-when-exhausted: false
      max-active: 10
      max-idle: 10
      max-wait: 1000
      min-evictable-idle-time-millis: 60000
      min-idle: 5
      num-tests-per-eviction-run: 1024
      soft-min-evictable-idle-time-millis: 10000
      test-on-borrow: true
      test-while-idle: true
      time-between-eviction-runs-millis: 30000
    port: 6379
    timeout: 2000

